#ifndef VERSION_HPP
#define VERSION_HPP

#define TACTICUS_VERSION_MAJOR  0
#define TACTICUS_VERSION_MINOR  1
#define TACTICUS_VERSION_PATCH  0

#define TACTICUS_VERSION_COMMIT

#define TACTICUS_STR_EXP(__A)   #__A
#define TACTICUS_STR(__A)       TACTICUS_STR_EXP(__A)
#ifdef TACTICUS_VERSION_INTERNAL
#   define TACTICUS_VERSION TACTICUS_VERSION_INTERNAL
#else
#   if TACTICUS_VERSION_PATCH
#       define TACTICUS_VERSION TACTICUS_STR(TACTICUS_VERSION_MAJOR) "." \
                              TACTICUS_STR(TACTICUS_VERSION_MINOR) "." \
                              TACTICUS_STR(TACTICUS_VERSION_PATCH)
#   else
#       define TACTICUS_VERSION TACTICUS_STR(TACTICUS_VERSION_MAJOR) "." \
                              TACTICUS_STR(TACTICUS_VERSION_MINOR)
#   endif
#endif
#endif